MAIN	=	test_mem_main.c

LIBFT	=	../../../libft/libft.a

SRCS	=	memset_test.c \
				bzero_test.c \
				memcpy_test.c \
				memccpy_test.c \
				memmove_test.c \
				memchr_test.c \
				memcmp_test.c

testMem:
	gcc -Wall -Werror -Wextra  $(MAIN) $(SRCS) $(LIBFT)
	./a.out
